spring.application.name=checkout-orchestrator
server.port=8082

resilience4j.circuitbreaker.instances.pago-api.sliding-window-size=5
resilience4j.circuitbreaker.instances.pago-api.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.pago-api.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.pago-api.permitted-number-of-calls-in-half-open-state=2

resilience4j.circuitbreaker.instances.envio-api.sliding-window-size=4
resilience4j.circuitbreaker.instances.envio-api.failure-rate-threshold=25
resilience4j.circuitbreaker.instances.envio-api.wait-duration-in-open-state=10s